<a href="https://colab.research.google.com/github/shahryar-karimi/python_start/blob/main/IML_CWH1_Q2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align="center">An Introduction to Machine Learning - 25737</h1>
<h4 align="center">Dr. Sajjad Amini</h4>
<h4 align="center">Sharif University of Technology, Spring 2023</h4>

# Problem Set 02

Welcome to your second assignment. This exercise gives you a brief introduction to Python. 


STUDENT NAME: shahryar karimi

STUDENT ID: 98100237

## Import 
>Put all of your imports for this file in the below cell.

In [30]:
### START CODE HERE ###
import numpy as np
import pandas as pd
### END CODE HERE ###

# Question 1

## Array creation
>Create the followings to numpy array:
* A: a 3\*3 array like this:
$$
A = \left(\begin{array}{cc} 
10 & 20 & 30\\
5 & 10 & 15\\
1 & 5 & 8
\end{array}\right)
$$ 
* B: a 3\*3\*4 that filled with the numbers start from 15 and have steps of 5 to the end. The array should be filled first along the first dimension then the second dimension and at last the third dimension. like this:
$$
B[:, :, 0] = \left(\begin{array}{cc} 
15 & 30 & 45\\
20 & 35 & 50\\
25 & 40 & 55
\end{array}\right)
$$ 

In [23]:
### START CODE HERE ###
a = [[10, 20, 30], [5, 10, 15], [1, 5, 8]]
A = np.array(a)
print(A)
print()
B = np.arange(1, 3 * 3 * 4 + 1) * 5 + 10
B = B.reshape((3, 3, 4), order = 'F')
print(B[:, :, 0])
### END CODE HERE ###

[[10 20 30]
 [ 5 10 15]
 [ 1  5  8]]

[[15 30 45]
 [20 35 50]
 [25 40 55]]


## Replacement
>Replace the last slice of array B (B[:, :, 3]) with values of A. Then print the result.

In [24]:
### START CODE HERE ###
B[:,:,3] = A.copy()
print(B[:, :, 0])
print(B[:, :, 1])
print(B[:, :, 2])
print(B[:, :, 3])
### END CODE HERE ###

[[15 30 45]
 [20 35 50]
 [25 40 55]]
[[ 60  75  90]
 [ 65  80  95]
 [ 70  85 100]]
[[105 120 135]
 [110 125 140]
 [115 130 145]]
[[10 20 30]
 [ 5 10 15]
 [ 1  5  8]]


## Axis Swap 
>Swap the first(B[:, :, 0]) and last(B[:, :, 3]) slice of the array B **only with one line of code**. Then print the result.

In [25]:
### START CODE HERE ###
c = B[:, :, 0].copy()
B[:, :, 0] = B[:, :, 3].copy()
B[:, :, 3] = c
print(B[:, :, 0])
print(B[:, :, 1])
print(B[:, :, 2])
print(B[:, :, 3])
### END CODE HERE ###

[[10 20 30]
 [ 5 10 15]
 [ 1  5  8]]
[[ 60  75  90]
 [ 65  80  95]
 [ 70  85 100]]
[[105 120 135]
 [110 125 140]
 [115 130 145]]
[[15 30 45]
 [20 35 50]
 [25 40 55]]


## Transposing 
>Transpose the array B elements in each slice. Then print the result.

In [26]:
### START CODE HERE ###
B[:, :, 0] = np.transpose(B[:, :, 0])
B[:, :, 1] = np.transpose(B[:, :, 1])
B[:, :, 2] = np.transpose(B[:, :, 2])
B[:, :, 3] = np.transpose(B[:, :, 3])
print(B[:, :, 0])
print(B[:, :, 1])
print(B[:, :, 2])
print(B[:, :, 3])
### END CODE HERE ###

[[10  5  1]
 [20 10  5]
 [30 15  8]]
[[ 60  65  70]
 [ 75  80  85]
 [ 90  95 100]]
[[105 110 115]
 [120 125 130]
 [135 140 145]]
[[15 20 25]
 [30 35 40]
 [45 50 55]]


## Matrix Multiplication
>Calculate the matrix multiplication of all slices of the array B. 
(B[:, :, 0] \* B[:, :, 1] \* B[:, :, 2] \* B[:, :, 3]). Then print the result.

>**Note**: the result should be a 3\*3 array. 

In [27]:
### START CODE HERE ###
print(np.matmul(np.matmul(np.matmul(B[:, :, 0], B[:, :, 1]), B[:, :, 2]), B[:, :, 3]))
### END CODE HERE ###

[[ 39375000  45851625  52328250]
 [ 88537500 103100625 117663750]
 [134437500 156550500 178663500]]


## Determinant
>Calculate the determinant of the array A and print it.

In [29]:
### START CODE HERE ###
print(np.linalg.det(A))
### END CODE HERE ###

0.0


# Question 2

## Loading dataset
>Load the IMDB-Movie-Data.csv file into a pandas dataframe and show its first 5 rows. Each row of this dataframe corresponds to one film.

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

## Actors/Actresses Activity
>For each Actors/Actresses caculate the number of movies in the dataframe, then sort the actors/actresses first by their number of movies in descending order and then by their name in ascending order. 

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

## Score Histogram
>Draw the histogram of metascores and ratings. 

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

## Correlations
>Calculate the correlation between rating, votes and metascore of the movies.
Is there any meaningful relation between these features? 

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

# Question 3

## File
> Craet a .txt file and name it "Name_actors". You must write the name of all actors/actresses in the IMDB-Movie-Data.csv file. Don't write a name multiple time and write each name in a new line.

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

# Question 4

## Plot
>You must plot the number of movies in each year according to the IMDB-Movie-Data.csv file. X-axis is year and y-axis show the number of movies in each year.
> set the x_label, y_label and title for your plot.

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

## Plot
>You must plot the cos(x) curve. plot 20 cycle of the curve. the frequency of first half of curve is 50 Hz and frequency of second lalf is 200 Hz. 
> set the x_label, y_label and title for your plot.

In [ ]:
### START CODE HERE ###

### END CODE HERE ###